config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'demo' => 'demo#index'        #The demo/index page gets rerouted to just /demo
  get 'demo/pageOne' => 'demo#pageOne'  #must include all views in demo here like this one

  get 'help' => 'help#index'    #The help/index page gets rerouted to just /help
  
  get 'pirate_hunts/myHunts' => 'pirate_hunts#myHunts' # use this syntax for adding on top of reseourceful stuff
  
  Rails.application.routes.draw do
    resources :qr_codes, only: [:new, :create]
    post "qr/codes/:id/new" => "qr_codes#new"
  end
  
  resources :hunts do
    resources :tasks
  end
  post 'hunts/:id/join' => 'hunts#join'
  

  resources :pirate_hunts
  resources :pirate_tasks
  post 'pirate_tasks/:id/reject' => 'pirate_tasks#reject'
  post 'pirate_tasks/:id/approve' => 'pirate_tasks#approve'


  root 'welcome#index'
 
  devise_for :users









end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def new
  end

  def create
    @qr = RQRCode::QRCode.new( qr_code_params[:text], size: 4)
  end

private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/qr_codes/create.html.erb
<!-- Page for the created QR code to be presented on-->
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>QR Code Created</h3> 
      <br>
      <div class="col-sm-8 col-sm-offset-2">
          <table class="qr-code">
            <% @qr.modules.each_index do |x| %>
              <tr>
              <% @qr.modules.each_index do |y| %>
               <% if @qr.dark?(x,y) %>
                <td class="black"/>
               <% else %>
                <td class="white"/>
               <% end %>
              <% end %>
              </tr>
            <% end %>
            </table>
            <br />
            <br />
            <%= link_to "New QR Code", new_qr_code_path %>
      </div>
    </div>
  </div>
</div>

app/views/qr_codes/new.html.erb
<!-- Page for the Admin to create a QR code with a certain text value -->

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>Create a QR Code</h3> 
      <br>
      <div class="col-sm-8 col-sm-offset-2">
       <%= form_for :qr_code, url: qr_codes_path do |f| %>
        <%= f.label :text, 'Add the value for the QR Code here' %>
        <%= f.text_field :text %>
        <%= f.submit :class => 'btn-capstone' %>
      <% end %>
      </div>
    </div>
  </div>
</div>