config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'demo' => 'demo#index'        #The demo/index page gets rerouted to just /demo
  get 'demo/pageOne' => 'demo#pageOne'  #must include all views in demo here like this one

  get 'help' => 'help#index'    #The help/index page gets rerouted to just /help
  
  get 'pirate_hunts/myHunts' => 'pirate_hunts#myHunts' # use this syntax for adding on top of reseourceful stuff
  
  Rails.application.routes.draw do
    resources :qr_codes, only: [:new, :create]
    post "qr/codes/:id/new" => "qr_codes#new"
  end
  
  resources :hunts do
    resources :tasks
  end
  post 'hunts/:id/join' => 'hunts#join'
  

  resources :pirate_hunts
  resources :pirate_tasks
  post 'pirate_tasks/:id/reject' => 'pirate_tasks#reject'
  post 'pirate_tasks/:id/approve' => 'pirate_tasks#approve'


  root 'welcome#index'
 
  devise_for :users









end

app/models/hunt.rb
=begin
The associations for Hunts are listed here. Every hunt can have multiple tasks linked to it as well as
many Pirate Hunts. Each Hunt also belongs to the User who created it.
=end
class Hunt < ActiveRecord::Base #Singular because it is a class
  has_many :tasks, :dependent => :destroy#, :class_name=> 'Task'
  has_many :pirate_tasks
  belongs_to :user#, :class_name=> 'Pirate' #This is for the author
  has_many :pirate_hunts, :dependent => :destroy

  validates :title, presence: true
  validates :start_time, presence: true
  validates :start_date, presence: true
  validates :end_time, presence: true
  validates :end_date, presence: true

  # Have a user join a hunt. Will return the PirateHunt (if any) and a symbol:
  #  :success if successfully joined the hunt
  #  :already_joined if the user had already joined the hunt
  #  :error if some error occurred while joining the hunt (while saving PirateHunt)
  def join(user)
    # Check if user has already joined the hunt
    phunt = PirateHunt.find_by(user_id: user.id, hunt_id: self.id)
    if phunt then return phunt, :already_joined end

    # There's probably a better way to do this..
    phunt = PirateHunt.create(hunt: self, user: user)

    if phunt.save
      # Create each PirateTask
      self.tasks.each do |task|
        PirateTask.create(task: task, hunt: self, user: user, pirate_hunt: phunt, answer_uploaded: false, completed: false).save
      end
      return phunt, :success
    else
      return phunt, :error
    end
  end
  
  #search
  def self.search(search)
    #searches by title, location, or username
    joins("INNER JOIN users ON users.id = hunts.user_id").where("title LIKE ? OR start_location LIKE ? OR display_name LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    #joining on users.id = hunts.id causes huge issues because those fields don't match up,
    #so I use users.id = hunts.user_id
  end

end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController

  #def myHunts
    #@hunt = Pirate_Hunt.find(params[:user])
    #@hunt = Hunt.new(hunt_params)
  #end
  
	#	when a hunt is published, for now we do not want the creator of the hunt to
	#	be able to add more tasks, because then we have to play catch-up with pirate_hunts
	#	and their pirate_tasks.
  
  def new
    @hunt = Hunt.new
  end

  def create
    @hunt = Hunt.new(hunt_params)
      
    if @hunt.save
      redirect_to(hunt_path(@hunt.id), notice: 'Hunt successfully created') #redirects to the show for that individual hunt that was just created
      flash.now[:notice] = "Hunt Successfully Created"
    else
      flash.now[:alert] = "One or More Required Fields Left Blank"
      render('new') #also maybe changes?
    end
  end

  # TODO index should only pass to the View Hunts that are both public and published
  # def index
  #   @hunts = Hunt.where(published: true, public: true) #for 'browse all' page
  # end
  def index
    @hunts = Hunt.all
    if params[:search]
      @hunts = Hunt.search(params[:search]).order("created_at DESC")
    else
      @hunts = Hunt.all.order("created_at DESC")
    end
  end
  # TODO possibly a routing issue
  # you should only be able to see a hunt either if you are a the creator
  # or if the hunt is public and published
  #	or if the hunt is private and published and you have been invited
  def show
    @hunt = Hunt.find(params[:id])
    @tasks = @hunt.tasks
	 @pirate_tasks = @hunt.pirate_tasks.where(completed: false, answer_uploaded: true)
  end

  def edit #if 'edit hunt' page is a thing
    @hunt = Hunt.find(params[:id])
  end

  def update
    @hunt = Hunt.find(params[:id])
    @hunt.update_attributes(hunt_params)
    redirect_to(:action => 'show', :id => @hunt.id)
    #took out if/else b/c would rather always redirect to hunt page, but w/ error message displayed on failure to update (UI functionality??)
  end

  def delete
  end

  def destroy
    Hunt.find(params[:id]).destroy
    redirect_to controller: 'welcome', :action => 'index'
  end

  # Moved from PirateHunts#create to here
  def join
    @hunt = Hunt.find(params[:id])
    unless @hunt
      # If hunt not found, redirect
      redirect_to(root_path, notice: 'Hunt not found')
      return
    end

    @pirate_hunt, result = @hunt.join(current_user)
    if result == :success
      redirect_to(pirate_hunt_path(@pirate_hunt.id), notice: 'Hunt successfully joined')
    elsif result == :already_joined
      redirect_to(root_path, alert: 'You are already participating in this hunt')
    elsif result == :error
      redirect_to(hunts_path, alert: 'Error occurred while joining hunt') #also maybe changes?
    end
  end

  private
  def hunt_params
   params.require(:hunt).permit(:title, :public, :published, :active, :start_date, :start_time, :end_date, :end_time, :start_location, :description, :user_id, :created_at, :updated_at)
  end
#end #ends the 'private' section
end #end of class

app/helpers/hunts_helper.rb
module HuntsHelper
end

app/views/hunts/_approval.html.erb
<%if pirate_task.task.task_type == 1 %>
	
	
	<%= pirate_task.task.prompt %>
	<br>
	<%= pirate_task.user.display_name %>
	
	<br>
	
	<%= image_tag pirate_task.submission.url(:medium) %>
<br /><br />
	<%= form_for pirate_task, url: approve_pirate_task_path(pirate_task.id), method: :post do |f| %>
		<%= f.hidden_field :id, :value => pirate_task.hunt_id %>
		<%= f.hidden_field :completed, :value => 'true' %>
		<%= f.submit "Approve this photo", :class => 'btn btn-capstone btn-block' %>
	<% end %>
<br /><br />
    <%= form_for pirate_task, url: reject_pirate_task_path(pirate_task.id), method: :post do |f| %>
      <%= f.hidden_field :completed, :value => 'false' %>
      <%= f.submit 'Reject this photo', :class => 'btn btn-red btn-capstone' %>
    <% end%>
    
<% end %>

app/views/hunts/_browse.html.erb
<li id="hunt-<%= hunt.id %>">
  <span class="title"><%=hunt.title%></span>
  <% unless hunt.pirate_hunts.exists?(:user_id => current_user.id)%>
<%= button_to 'Join Hunt', { :controller => 'hunts', :action => 'join', :id => hunt.id}, :method => :post, :class => 'btn btn-capstone btn-block' %>
  <%end%>
  <span class="author">Created by <%=hunt.user.display_name%>.</span>
  <span class="description"><%= hunt.description %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(hunt.created_at) %> ago.
  </span>
</li>

app/views/hunts/_hunt.html.erb
<li id="hunt-<%= hunt.id %>">
  <span class="title"><%=link_to hunt.title, hunt %></span>
  <!--<% unless hunt.pirate_hunts.exists?(:user_id => current_user.id)%>
  You can join this hunt!
  <%end%>-->
  <span class="author">Created by <%=hunt.user.display_name%>.</span>
  <span class="description"><%= hunt.description %></span>
  <span class="timestamp">
    Created <%= time_ago_in_words(hunt.created_at) %> ago.
  </span>
</li>

app/views/hunts/create.html.erb
<h1>Hunts#create</h1>
<p>Find me in app/views/hunts/create.html.erb</p>

app/views/hunts/delete.html.erb
<h1>Hunts#delete</h1>
<p>Find me in app/views/hunts/delete.html.erb</p>

app/views/hunts/destroy.html.erb
<h1>Hunts#destroy</h1>
<p>Find me in app/views/hunts/destroy.html.erb</p>

app/views/hunts/edit.html.erb
<h1>Hunts#edit</h1>
<p>Find me in app/views/hunts/edit.html.erb</p>

app/views/hunts/index.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= google_webfonts_init({
    google: ['Quicksand', 'Quicksand']
  }) %>
</head>
<body>
<div class="container"> 
	<div class="row">
		<div class="col-sm-12" style="padding:0;">
            <%= form_tag(hunts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search by hunt title, creator, or location" %>
                <%= submit_tag "Search", :name => nil, :class => 'btn-capstone' %>
            <% end %>
        </div>
		<div class="col-md-10 col-md-offset-1 text-center">
			<% if @hunts.blank? %>
				<!--<h2>There are no hunts containing the term <%= params[:search] %>.</h2>-->
					<h2>No hunts found.</h2>
			<% end %>
			<h2>Hunt List</h2>
			<ol class="hunts"><%= render partial: "browse", collection: @hunts, as: 'hunt' %></ol>
			<br>

			<div class="text-center">
			<%= link_to 'Create a Hunt', new_hunt_path, :class => 'btn btn-capstone btn-block'%> 
			</div>
		</div>
	</div>
</div>	
</body>
</html>

app/views/hunts/new.html.erb
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

			<div class="text-center">
				<!-- Create a Hunt Icon --->
				<%=image_tag("paintbrush.svg", :class => "img-circle")%>

			</div>
<div class="row">
	<div class="container">
		<div class= "col-md-10 col-md-offset-1">

			

			<h3>Let's create a hunt</h3>
			<br>
			<%= form_for(@hunt) do |f| %>
					  
					  <%= f.label :title, "*Title:"%>
					  <%= f.text_field :title %>
					  <br>

					  
				
						  <%= f.hidden_field :active, :value => false %>
					  
						  <%= f.hidden_field :published, :value => false %>
						  
						  <%= f.hidden_field :public, :value => true %>
					  
					<!-- Creating another small col for the timepickers to be placed in a more user friendly layout-->
					<div class="col-xs-12">
						<div class="col-xs-6">
							<%= f.label :start_date, "*Start Date:" %><br>
					  		<%= f.date_field :start_date %>
						</div>
						<div class="col-xs-6">
							<%= f.label :end_date, "*End Date:" %><br>
					  		<%= f.date_field :end_date %>
						</div>
						<div class="col-xs-6">
							<%= f.label :start_time, "*Begins at:"%><br>
					  		<%= f.time_field :start_time %>
						</div>
						<div class="col-xs-6">
							<%= f.label :end_time, "*Ends at:"%><br>
					  		<%= f.time_field :end_time %>
						</div>
					</div>
					  <br>
					  <%= f.label :start_location, "Start Location:"%>
					  <%= f.text_field :start_location%>
					  <br>
					  <%= f.label :description, "Description:"%>
					  <%= f.text_field :description%>
					  <br>
					  <%= "*=Required" %><br>
					  <%= f.hidden_field :user_id, :value => current_user.id%>
					  <%= f.hidden_field :created_at%>
					  <%= f.hidden_field :updated_at%>
					  <br>
					
					  <%= f.submit "Create Hunt", class: "btn btn-capstone btn-block" %>
					  <br>
					  <br>
					 
					<% end %>
				</div>
			</div>
		</div>

app/views/hunts/show.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<div class="container">
    <div class="row">
		<div class="col-sm-10 col-md-10 col-md-offset-1 col-lg-10">
            <div class = "text-center"> 
			<h3><%= @hunt.title.upcase%></h3><%#The title of the hunt will be the header of the page%>
			


<!-- <h2><%= @hunt.description%></h2><%#The description will be directly beneath the hunt title for easy readability%>
<br><br>
<p>This hunt starts at <%=@hunt.start_location%></p> -->

<%= @hunt.description%><%#The description will be directly beneath the hunt title for easy readability%>
<br>
This hunt starts at <%=@hunt.start_location%>
<br>
<%#This displays the start and end times of the hunt%>
The hunt begins on <%= @hunt.start_date.to_s(:long)%> at <%=@hunt.start_time.strftime("%I:%M %p")%> and <br> ends on <%= @hunt.end_date.to_s(:long)%> at <%=@hunt.end_time.strftime("%I:%M %p")%>

<br><br><br>

<%#This displays whether the hunt is public or private, but we aren't currently using this %>
<!-- <p><% if(@hunt.public?) %><div class="public">This hunt is a public hunt</div><% else %><div class="private">This hunt is a private hunt </div><%end%></p> -->


<%#This is meant to display whether or not the hunt is active based on the active bool, apparently this is supposed to be hidden as well%>
<!-- <p><% if(@hunt.active?) %><div class="active">This hunt is currently active</div><% else %><div class="inactive">This hunt is currently not active </div><%end%></p> -->

<%#Currently the public and active displays are not staying in line with the rest of the paragraphs, but that is a stylesheet issue and will be fixed later%>

<%= render @tasks %>

<p></p>

<br>
<%if @hunt.user_id == current_user.id%>
	<%= button_to 'Delete Hunt', hunt_path, :method => 'delete', :class => 'btn btn-capstone btn-red btn-block'%>
<%end%>

<br>

<%# is the if statement enough to prevent the creator from creating tasks after
	the hunt is published or should we make it more secure?%>
<%if @hunt.user_id == current_user.id && @hunt.active == false%>
	<%= button_to 'Create Task', new_hunt_task_path(@hunt), :method => 'get', :class => 'btn btn-capstone btn-block'%>
<%end%>

<%# We don't need this button, do we? %>
<%#= button_to 'View Tasks', hunt_tasks_path(@hunt), :method => 'get', :class => 'btn btn-capstone btn-block'%>

<%# The button for publishing a may need to be moved so that only creators of a hunt can publish %>
<%# Also, we probably want to hide these buttons once their fields are set to true so you cannot
	republish/reactivate a hunt over and over%>

<%if @hunt.published == false && @hunt.user_id == current_user.id%>
    <br>
	<%= button_to 'Publish Hunt', {:controller => 'hunts', :action => 'update', :hunt => {:published => 'true'}}, :method => :put, :class => 'btn btn-capstone btn-block' %>
<%end%>

<br>
<%# Do we need to add some sort of check that makes the creator publish the hunt before%
	making it Active?%>
<%if @hunt.active == false && @hunt.user_id == current_user.id && @hunt.published == true%>
	<%= button_to 'Activate Hunt', {:controller => 'hunts', :action => 'update', :hunt => {:active => 'true'}}, :method => :put, :class => 'btn btn-capstone btn-block' %>
<%end%>

<%if @hunt.active == true %>

	<h3>Images for Approval</h3>

	<%= render(partial: "approval", collection: @pirate_tasks, as: "pirate_task") || "There's nothing to be displayed" %>
<%end%>

			</div>
		<div>
	</div>
</div>

app/views/hunts/update.html.erb
<h1>Hunts#update</h1>
<p>Find me in app/views/hunts/update.html.erb</p>