config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'demo' => 'demo#index'        #The demo/index page gets rerouted to just /demo
  get 'demo/pageOne' => 'demo#pageOne'  #must include all views in demo here like this one

  get 'help' => 'help#index'    #The help/index page gets rerouted to just /help
  
  get 'pirate_hunts/myHunts' => 'pirate_hunts#myHunts' # use this syntax for adding on top of reseourceful stuff
  
  Rails.application.routes.draw do
    resources :qr_codes, only: [:new, :create]
    post "qr/codes/:id/new" => "qr_codes#new"
  end
  
  resources :hunts do
    resources :tasks
  end
  post 'hunts/:id/join' => 'hunts#join'
  

  resources :pirate_hunts
  resources :pirate_tasks
  post 'pirate_tasks/:id/reject' => 'pirate_tasks#reject'
  post 'pirate_tasks/:id/approve' => 'pirate_tasks#approve'


  root 'welcome#index'
 
  devise_for :users









end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@created_hunts = Hunt.where(user_id: current_user.id)
  	@joined_hunts = PirateHunt.where(user_id: current_user.id)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= google_webfonts_init({
    google: ['Quicksand', 'Quicksand']
  }) %>
</head>

<!-- Marketing messaging and featurettes 
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<% provide(:title, 'Home') %>
<div class="container">
	<div class="row>
		<div class ="col-md-10 .col-md-offset-1 text-center">
		<!-- ========================================== -->
	         <div class="panel-group" id="accordion">
					<div class="huntsHeader">
					<h2>Hunts</h2>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">
								<h4 class="panel-title">
								<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
								Created Hunts </a>
                                </h4>
                            </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    <ol class="hunts"><%= render @created_hunts %></ol>
                </div>
            </div>
        </div>
		<!-- ===========================================--> 
	    <!-- =========================================== -->
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">
								<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTen">Joined Hunts</a>
							</h4>
						</div>
						<div id="collapseTen" class="panel-collapse collapse">
							<div class="panel-body">
							   <%#calls pirate_hunt partial %>
							   <ol class="hunts"><%= render @joined_hunts %></ol>
							</div>
						</div>
					</div>
		<!-- =========================================== -->
	
		</div>
        <div class="col-sm-12" style="padding:0;">
            <%= form_tag(hunts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search by hunt title, creator, or location" %>
                <%= submit_tag "Search", :name => nil, :class => 'btn-capstone' %>
            <% end %>
        </div>
	</div>
</div>	

<div class="container marketing">
  <hr class="featurette-divider">
  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-md-3 text-center">
    <div class="home-option">
    	<%= link_to image_tag("browse-hunts.svg", :class => "img-circle"), hunts_path %>
    	<h2>Browse Hunts</h2>
        <h4>See which hunts you wish to join.</h4>
	  	<p><%= link_to 'Join Hunts »', hunts_path, :class => 'btn btn-capstone btn-block'%> </p>
    </div>
    </div>
    <div class="col-md-3 text-center">
	<div class="home-option">
        <%= link_to image_tag("paintbrush.svg", :class => "img-circle"), new_hunt_path %>
        <h2>Create a hunt</h2>
        <h4>Can't find a hunt that suits you?</h4>
        <p><%= link_to 'Make your Own »', new_hunt_path, :class => 'btn btn-capstone btn-block'%></p>
	</div>
    </div>
    
   
    <!--Admin if statement goes here-->
    <div class="col-md-3 text-center">
	<div class="home-option">
        <%= link_to image_tag("phone.svg", :class => "img-circle"), new_hunt_path %>
        <h2>Create QR</h2>
        <h4>Create QR codes for hunts task</h4>
        <p><%= link_to "New QR Code", new_qr_code_path, :class => 'btn btn-capstone btn-block'%></p>
	</div>
    </div>

    
    
    <div class="col-md-3 text-center">
    <div class="home-option">
        <%= link_to image_tag("ipad.svg", :class => "img-circle"), demo_path %>
        <h2>Try a Tutorial</h2>
        <h4>This tutorial will show you the ropes.</h4>
        <p><%= link_to 'Start Here »', demo_path, :class => 'btn btn-capstone btn-block'%></p>   
    </div>
    </div>
  </div><!-- /.row -->