config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'

  get 'qr_codes/create'

  get 'demo' => 'demo#index'        #The demo/index page gets rerouted to just /demo
  get 'demo/pageOne' => 'demo#pageOne'  #must include all views in demo here like this one

  get 'help' => 'help#index'    #The help/index page gets rerouted to just /help
  
  get 'pirate_hunts/myHunts' => 'pirate_hunts#myHunts' # use this syntax for adding on top of reseourceful stuff
  
  Rails.application.routes.draw do
    resources :qr_codes, only: [:new, :create]
    post "qr/codes/:id/new" => "qr_codes#new"
  end
  
  resources :hunts do
    resources :tasks
  end
  post 'hunts/:id/join' => 'hunts#join'
  

  resources :pirate_hunts
  resources :pirate_tasks
  post 'pirate_tasks/:id/reject' => 'pirate_tasks#reject'
  post 'pirate_tasks/:id/approve' => 'pirate_tasks#approve'


  root 'welcome#index'
 
  devise_for :users









end

app/views/layouts/_altNavBar.html.erb
<!-- This simply changes the color of the text on the navbar when it's not hovered on-->
<style>
ul li a {
  color: black;
}
</style> 

<div class="span12 text-center">
	<% if user_signed_in? %>
		<ul class="nav nav-pills center-pills">
			<li><%= link_to "Home", root_path %></li>
			<li role="presentation" class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
				<strong><%= current_user.display_name %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Edit profile', edit_user_registration_path%></li>
				<li><%= link_to "Return to Application", root_path %></li>
			</ul>
  		</li>
		<li role="presentation" class="dropdown">
    			<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
			<strong><%= 'Help' %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Help', help_path%></li>
				<li><%= link_to 'Tutorial', demo_path%></li>
			</ul>
  		</li>
	</ul>

	<% else %>
	<ul class="nav nav-pills center-pills navbar-text">
		<li><%= link_to "Sign up", new_user_registration_path %></li>
		<li><%= link_to "Login", new_user_session_path %></li>
	
		<li role="presentation" class="dropdown">
    			<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
			<strong><%= 'Help' %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Help', help_path%></li>
				<li><%= link_to 'Tutorial', demo_path%></li>
			</ul>
  		</li>
	
	<% end %> 
</div>

app/views/layouts/_navbarHeader.html.erb
<!-- This simply changes the color of the text on the navbar when it's not hovered on-->
<style>
ul li a {
  color: black;
}
</style> 

<div class="span12 text-center">
	<% if user_signed_in? %>
	<ul class="nav nav-pills center-pills">
		<li><%= link_to "Home", root_path %></li>
  		<li role="presentation" class="dropdown">
    			<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
			<strong><%= current_user.display_name %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Edit profile', edit_user_registration_path%></li>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
			</ul>
  		</li>
		<li role="presentation" class="dropdown">
    			<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
			<strong><%= 'Help' %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Help', help_path%></li>
				<li><%= link_to 'Tutorial', demo_path%></li>
			</ul>
  		</li>
	</ul>
	<% else %>
	<ul class="nav nav-pills center-pills">
		<li><%= link_to "Sign up", new_user_registration_path %></li>
		<li><%= link_to "Login", new_user_session_path %></li>
	
		<li role="presentation" class="dropdown">
    			<a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
			<strong><%= 'Help' %></strong>

			<span class="caret"></span>
			</a>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Help', help_path%></li>
				<li><%= link_to 'Tutorial', demo_path%></li>
			</ul>
  		</li>
	
	<% end %> 
</div>

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Capstone2015</title>	
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
    google: ['Quicksand', 'Quicksand']
  }) %>
</head>

<body>

<!--- The id tag here is an anchor tag for the footer. By pressing "back to top" in the footer, the page jumps up to this tag --->
<id="top">
<%= render 'layouts/navbarHeader' %>
<!--< %= form_tag(hunts_path, :method => "get", id: "search-form") do %>-->
<!--    < %= text_field_tag :search, params[:search], placeholder: "Search by hunt title or location" %>-->
<!--    < %= submit_tag "Search", :name => nil %>-->
<!--< % end %>-->
</id>
<div class="wrapper">
<div class="container">

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

  <%= yield %>

</body>

</html>